live_config_reload = true

[env]
# These variables are added as environment variables for any process spawned by Alacritty
TERM = "xterm-256color"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.88
startup_mode = "Windowed"
title = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 14.0

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x111111"
foreground = "0xeaeaea"

[colors.cursor]
cursor = "0xffffff"
text = "0x000000"

[colors.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0ba"
green = "0xb9ca4a"
magenta = "0xc397d8"
red = "0xd54e53"
white = "0xffffff"
yellow = "0xf9ec2c"

[colors.bright]
black = "0x666666"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0xffffff"
yellow = "0xe7c547"

[colors.dim]
black = "0x333333"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xf2777a"
white = "0xdddddd"
yellow = "0xffcc66"

[bell]
animation = "EaseOutSine"
color = "#ffffff"
duration = 120
