#!/usr/bin/env bash
set -eo pipefail

if [[ "$1" == "up" ]]; then
  sudo systemctl stop openvpn-client@threema.service
  sudo systemctl start openvpn-client@threema.service
elif [[ "$1" == "down" ]]; then
  sudo systemctl stop openvpn-client@threema.service
elif [[ "$1" == "tail" ]]; then
  sudo journalctl -f -u openvpn-client@threema.service
else
  echo "Usage: vpn (up|down|tail)"
fi
